Add libcifpp as dependency and ensure DSSP annotation
conda-forge/dssp-feedstock pull request #4
Opened 2024-10-14 12:00 UTC by padix-key

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2024-10-14 12:02 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe/meta.yaml```) and found it was in an excellent condition.

2024-10-14 14:50 UTC, mhekkel commented
> @mhekkel The library is only required during runtime and not for compilation, right?

Nope. The library is included by the cmake file of dssp and build during the build phase. There was an issue with the dictionary not being installed. Normally the process uses [mrc](https://github.com/mhekkel/mrc) to bundle this file as a resource but apparently conda does not use mrc, and mrc does not work on macOS. So I recently released a new dssp and libcifpp that does install the dictionary during the install phase of dssp. In case you did not have libcifpp installed already.

Hope this makes sense?

2024-10-14 21:34 UTC, padix-key commented
Thanks for the explanation. Could you elaborate how I need to adapt the build script?

> So I recently released a new dssp and libcifpp that does install the dictionary during the install phase of dssp

Does 'install phase' refer to the compilation, i.e. is any linking required during compilation or are just some required files put into some directory, that are used during run time?

2024-10-15 06:54 UTC, mhekkel commented
> Thanks for the explanation. Could you elaborate how I need to adapt the build script, when I do not use `mrc`?

Theoretically, the latest version of dssp as taken from github should install a dictionary file by default.

However, I just noticed I did not include that fix in a release yet so I had to create a new release. Version number is now 4.4.9. Please update the code.

> > So I recently released a new dssp and libcifpp that does install the dictionary during the install phase of dssp
> 
> Does 'install phase' refer to the compilation, i.e. is any linking required during compilation or are just some required files put into some directory, that are required when `mkdssp` is actually executed?

There is one file that is needed to run mkdssp and that is the mmcif_pdbx dictionary file.

dssp uses libcifpp to load so-called resources. The way they work is documented here:

https://pdb-redo.github.io/libcifpp/resources.html

2024-10-15 08:26 UTC, padix-key commented
In the newest DSSP version, the build fails with

```
CMake Error at build/cmake_install.cmake:75 (file):
  file INSTALL cannot find
  "/home/conda/feedstock_root/build_artifacts/.../share/libcifpp/mmcif_pdbx.dic":
  No such file or directory.
```

2024-10-15 09:04 UTC, mhekkel commented
> With the newest DSSP version, the build fails with
> 
> ```
> CMake Error at build/cmake_install.cmake:75 (file):
>   file INSTALL cannot find
>   "/home/conda/feedstock_root/build_artifacts/.../share/libcifpp/mmcif_pdbx.dic":
>   No such file or directory.
> ```

That's curious, there are three dots in that path. Where do they come from? The variable used to create this path comes from these lines in CMakeLists.txt of libcifpp:

```cmake
	set(CIFPP_DATA_DIR
		"${CMAKE_INSTALL_FULL_DATADIR}/libcifpp"
		CACHE PATH "Directory where dictionary and other static data is stored")
```

Which is then later on passed to the dssp makefile using:

```cmake
if(NOT PROJECT_IS_TOP_LEVEL)
	set(CIFPP_SHARE_DIR ${CIFPP_DATA_DIR} PARENT_SCOPE)
endif()
```

Perhaps this info helps to debug the problem? The CMAKE_INSTALL_FULL_DATADIR contains those three dots already, most likely, but why?

2024-10-15 09:47 UTC, padix-key commented
I actually added the `...` to abbreviate the long `placehold_placehold_...` path the conda build uses to put build artifacts.

The original error message is here: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1054794&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3&l=892

2024-10-16 06:06 UTC, mhekkel commented
OK, I made an error in the makefiles. I will have to fix both libcifpp and dssp, again.

2024-10-16 06:18 UTC, mhekkel commented
Please use version 4.4.10 of dssp. That should fix this issue.

2024-10-16 06:41 UTC, padix-key commented
Many thanks!

2024-10-16 07:18 UTC, padix-key commented
I fear something is still wrong with the internal CCD:

The linux build as well as the windows build complains about the file itself:

```
Error while loading dictionary mmcif_pdbx
 >> basic_filebuf::underflow error reading the file: Is a directory
```
(https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1055942&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3&l=949)


```
Error while loading dictionary mmcif_pdbx
 >> Dictionary not found or defined (mmcif_pdbx)
```
(https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1055942&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=6119ccbe-9301-594f-7c27-f792b80a7fcc&l=2813)

The OSX build, while passing, has still problems finding the components for any residue (including all amino acids) in the test structure:

```
Unknown compound: ALA
Unknown compound: ARG
Unknown compound: ASN
Unknown compound: ASP
Unknown compound: CYS
Unknown compound: GLN
Unknown compound: GLU
Unknown compound: GLY
Unknown compound: HIS
Unknown compound: HOH
Unknown compound: ILE
Unknown compound: LEU
Unknown compound: LYS
Unknown compound: MET
Unknown compound: PHE
Unknown compound: PRO
Unknown compound: SER
Unknown compound: THR
Unknown compound: TRP
Unknown compound: TYR
Unknown compound: VAL
Missing compound information for LYS
Missing compound information for VAL
Missing compound information for PHE
Missing compound information for GLY
Missing compound information for ARG
Missing compound information for CYS
Missing compound information for GLU
Missing compound information for LEU
Missing compound information for ALA
Missing compound information for MET
Missing compound information for HIS
Missing compound information for ASP
Missing compound information for ASN
Missing compound information for TYR
Missing compound information for SER
Missing compound information for TRP
Missing compound information for GLN
Missing compound information for ILE
Missing compound information for PRO
Missing compound information for HOH
```
(https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1055942&view=logs&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=933f325c-924e-533d-4d95-e93b5843ce8b&l=1336)

2024-10-16 08:23 UTC, mhekkel commented
I know nothing about the way conda installs software. But I get the scary feeling that the final destination of files is not what the code expects based on configuration parameters.

Is it possible to see what is actually installed, including full paths? And is it possible to get these files in a zip/tar/archive?

As a workaround, you might try to set the environmental variable for cifpp resources as described in the resources documentation I mentioned earlier.

I don't have much time to work on this for at least two weeks, so I hope you can find a fix. Else it will have to wait.

2024-10-16 16:03 UTC, padix-key commented
No problem, I might try a local build, where I have better control over the environment, when I have some spare time.

2025-03-01 20:57 UTC, mhekkel requested changes
The code is not working on other platforms than macOS, as far as I can see. The problem is loading resources. See https://www.hekkelman.net/libcifpp-doc/resources.html for more info on how libcifpp based tools find their data files.

Anyway, the build log shows that the file mmcif_pdbx.dic is installed, but the application mkdssp cannot find it. So there is a conflict in the location libcifpp expects and the actual location.

Is it possible to get access to what was built on Azure? To do post mortem debugging, dissecting the executable to find out where it expects the data to be and compare it to the actual location where this data was installed.

2025-03-05 23:04 UTC, padix-key commented
Sorry, I missed your comment. Unfortunately it is not possible to access the CI build directories, if I am not completely wrong.

I read a bit into the Conda build process and found [this](https://docs.conda.io/projects/conda-build/en/stable/concepts/recipe.html#conda-build-process):

> Creates a conda package containing all the files in the build environment that are new from step 5, along with the necessary conda package metadata.

> Deletes the build environment and source directory to ensure that the new conda package does not inadvertantly depend on artifacts not included in the package.

My suspicion would be that
- either `libcifpp` uses a absolute path instead of a relative one to refer to the CCD files,
- or that `libcifpp` does not write the CCD files into the build environment
Is any of these assumptions true?

2025-03-05 23:20 UTC, padix-key commented
I just unpacked the latest `linux-64` package from [here](https://anaconda.org/conda-forge/dssp/files) and found that `shar/libcifpp/mmcif_pdbx.dic` is present.

2025-03-05 23:56 UTC, padix-key commented
I temporarily define the path to `share/libcifpp/mmcif_pdbx.dic` manually in the tests to test the hypothesis that another file location is expected. So now it runs

```
mkdssp 1aki.cif 1aki_dssp.cif --mmcif-dictionary /home/conda/feedstock_root/build_artifacts/dssp_1741217896472/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/share/libcifpp/mmcif_pdbx.dic
```

Interestingly it still errors with

```
basic_filebuf::underflow error reading the file: Is a directory
``` 

This would indicate that the actual code sees this path and for some reason thinks it is a directory instead of a file, right?

By the way, here is the explanation for the `placehold` repeats: https://github.com/conda/conda-build/issues/1482

2025-04-10 07:57 UTC, mhekkel commented
Looking at the logs I see that on linux and windows the cmake configure step is not executed. Hence the build directory is missing since that would have been created by cmake configure. This looks like a configuration error in this _feedstock_.

2025-05-16 15:28 UTC, mhekkel commented
I've been investigating this a bit today. Seems like the hack conda uses to make packages re locatable is not working with libcifpp. Until that is fixed (either in the recipe file or in libcifpp) this feedstock is not going to work.

2025-05-16 15:28 UTC, closed without merging

2025-05-20 16:21 UTC, padix-key commented
Thanks for investigating this!